---
- name: apt get update
  apt: update_cache=yes

- name: Install letsencrypt client (formerly certbot)
  apt: name=letsencrypt
  
- name: Insert template presetup
  template: src=site_pre_config.j2 dest=/etc/nginx/sites-available/{{letsencrypt_domain_name}}

- name: Ensure directory exists
  file: path=/var/www/{{letsencrypt_domain_name}} state=directory

- file: src=/etc/nginx/sites-available/{{letsencrypt_domain_name}} dest=/etc/nginx/sites-enabled/{{letsencrypt_domain_name}} state=link
    
- name: restart
  service: name=nginx state=restarted
  
- name: Run letsencrypt
  command: letsencrypt certonly -a webroot --webroot-path=/var/www/{{letsencrypt_domain_name}} -d {{letsencrypt_domain_name}} -n --agree-tos --email {{letsencrypt_email}}
  
- stat: path=/etc/ssl/certs/dhparam.pem
  register: stat_res

- name: Generate strong Diffie-Hellman Group if it doesnt exists
  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
  when: stat_res.stat.exists == False
  
- name: setup ssl-params.conf
  template: src=ssl_params.j2 dest=/etc/nginx/snippets/ssl-params.conf

- name: setup 
  template: src=ssl_conf.j2 dest=/etc/nginx/snippets/ssl-{{letsencrypt_domain_name}}.conf

- name: Copy file
  template: src={{nginx_config_name}} dest=/etc/nginx/sites-available/{{letsencrypt_domain_name}}

- name: enable site
  file: src=/etc/nginx/sites-available/{{letsencrypt_domain_name}} dest=/etc/nginx/sites-enabled/{{letsencrypt_domain_name}} state=link
  
- name: Setup cron job which renews the certificate 
  cron: 
    name: "{{item.name}}"
    job: "{{item.job}}"
  with_items:
    - name: Renew letsencrypt
      job: 30 2 * * 1 /usr/bin/letsencrypt renew >> /var/log/le-renew.log
    - name: Reload nginx after letsencrypt renewal
      job: 35 2 * * 1 /bin/systemctl reload nginx

- name: reload nginx
  service: name=nginx state=reloaded
